### PR TITLE
newsweek website clone

### PR DESCRIPTION
**Pull request by Zubenna**
# Newsweek.com clone project: Summary of work done
## In this project I did the following;
- I set up the detailed layout of the web page using semantic HTML5 elements.
- I arranged different units of the webpage in groups. 
- I used bootstrap layout classes to arrange columns in each group.
- I used CSS flex-box and grid to further arrange each group and sub-group where necessary.
- Added required pictures and background images where necessary.
- Applied bootstrap classes for padding, margin, position, text-alignment, etc where necessary.
- Used media query to apply responsiveness at bootstrap breakpoints for extra small width, small width, medium width, and large screen sizes.

### CODE REVIEW

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @Zubenna  :wave:
-
You have done a splendid job! :tada: Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
## Notes: The clone shows good use of using bootstrap 💯
1. The project has a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)) which is professionally done and well documented.
2. The Pull Request has a meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).
3. The Commits are descriptive ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_commits.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
4.  Good usage of [semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp) elements which are appropriately sized and positioned (as described in Odin project description) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/semantic_html_requirement.png) from Pathwright).
5. CSS is clean. No linter errors at this point and no bad practices used as well.
6.  The markup as well has no errors nor warnings to show. Good job with that.
##

## [REQUIRED] - Fix - The Following areas.
Note that for this project, we have to make sure nothing is messed up. Please see the difference in the source page and the clone below: 

**(I am conducting this review with a (1920 x 1080) screen display resolution.)**

| [Current clone](https://raw.githack.com/Zubenna/newsweek-clone/feature-branch/index.html) | [Source Page](https://www.newsweek.com/) |
|:-----:|:-----:|
| clone| newsweek|
- The contents of the page are not properly centred as is expected. Let's fix this. Hint: **The `container` class could come i handy here.**
##
| [Current clone](https://raw.githack.com/Zubenna/newsweek-clone/feature-branch/index.html) | [Source Page](https://www.newsweek.com/) |
|:-----:|:-----:|
|top-story-clone|top-story|
- Artciles below the top story section are widely spaced make them compact as seen in the source page.
##
| [Current clone](https://raw.githack.com/Zubenna/newsweek-clone/feature-branch/index.html) | [Source Page](https://www.newsweek.com/) |
|:-----:|:-----:|
|in-the-magazine-clone|in-the-magazine|
- Remove the spacing between the articles in the 'in the magazine' section.
##
| [Current clone](https://raw.githack.com/Zubenna/newsweek-clone/feature-branch/index.html) | [Source Page](https://www.newsweek.com/) |
|:-----:|:-----:|
|editors-pick-clone|editors-pick|
- Fix the editors pick section as well.
##
| [Current clone](https://raw.githack.com/Zubenna/newsweek-clone/feature-branch/index.html) | [Source Page](https://www.newsweek.com/) |
|:-----:|:-----:|
|footer-clone|footer|



#### :recycle:  Make these changes and submit another code review request. :+1: 
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes: Good luck with your next submission. :star2:  
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

**Comment by Zubenna** [comment]
Recommended changes has been implemented.

**Comment by Zubenna** [comment]
Recommended changes has been implemented.

**Comment by uryelah** [comment]
Hello **Nnamdi Emelu**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all great job with this project! Your clone and use of Boostrap are both very good.🌟**

There are still some issues to fix before moving on, remember that this project should look as close as possible to the[ original page](https://www.newsweek.com/), so read the requirements below carefully and keep your code game strong 💪 

---------     

## Required Changes 🏗 👷‍♀ 

- [ ] Pay extra attention to the text weight of your page compared to the original one. If you notice any differences try to change it with bootstrap classes.

- [ ]  Good job limiting the width of the page, but the background, at the sides, in the desktop size should be grey. Compare your clone the original page below:
Screenshot_2020-04-26 Newsweek-clone
Screenshot_2020-04-26 Newsweek


----

- [ ] The sections above the 'In the Magazine' section should all be aligned at the bottom, no white space, regardless of them having different heights. You could use a vertical scroll to fix it.
**Your version, notice the white space:**
Screenshot_2020-04-26 Newsweek-clone(1)
**Original:**
Screenshot_2020-04-26 Newsweek(1)


------

- [ ] Make sure your navbar is fixed at the top like on the original page.
- [ ] Make sure the Newsletter image is not getting distorted. It should keep it's proportions.
Compare below how in your clone it looks squeezed and in the original one it keeps it horizontal proportion:
Screenshot_2020-04-26 Newsweek-clone(2)
Screenshot_2020-04-26 Newsweek(2)


-----

- [ ] Make sure that the navbar items have the same alignment than the original site in medium screens:
- [ ] Style the 'hamburger' menu the same as the original one:
Screenshot_2020-04-26 Newsweek-clone(3)

Uploading Screenshot_2020-04-26 New
![Screenshot_2020-04-26 Newsweek(3)


----

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by Zubenna** [comment]
Required changes have been implemented.

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi @Zubenna  👋

Your project looks awesome so far. 🚀

Kindly fix these issues as we are just a few steps away from a thumbs-up. 
Hand in there, you've got this.💪

- [ ] Please remove the `!important` tag declaration you have in your CSS file. We generally want to avoid using the `!important`, refer to this ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright). 
**THIS IS YOUR CSS CODE**👇
ice_screenshot_20200429-023201
ice_screenshot_20200429-023210

- [ ] Consider removing the scrollbar that appears in the middle of your webpage. You can refer to [this StackOverflow post](https://stackoverflow.com/questions/43186015/css-hide-scroll-bar-but-have-element-scrollable/43186311) post for tips.
[SCREENSHOT]👇
ice_screenshot_20200429-022712

**Once again, your project looks great.👏👏**

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by Zubenna** [comment]
Required recommendations have been implemented.

**Comment by lekegitrepo** [comment]
#### Hi @Zubenna :clap: 
#### Good job so far. The page looks great but you need to fix the horizontal scroll on the page. Check the image below :point_down: 

Screenshot from 2020-04-29 03-53-08

**_if you press the right arrow key the page almost scrolls out of the view._**

**_fix this and submit for review._**

### Reviewed by Temitayo Adeleke.

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Request changes

**Comment by Zubenna** [comment]
Required change has been implemented.

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Hi @Zubenna  👋

You've really done well on this project.

However, kindly fix this single issue.

- [ ] In a previous review you were requested to remove the scrollbar on just one particular section but instead, it seems as though you also mistakenly removed the scrollbar on the `body` element as well.
The issue is you attached the code to remove the scrollbar on no particular container that's why it applied to all elements even the `body` element. Check [this link](https://www.w3schools.com/css/css_pseudo_classes.asp) on how to attach a pseudo-element selector to an element.
**THIS IS YOUR CODE KINDLY ATTACH IT TO THE RIGHT ELEMENT**
ice_screenshot_20200429-192152


**Once more you've really done well on this** The front-end looks awesome.🚀

Kindly fix these issue and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by Zubenna** [comment]
Required change has been implemented.

**Comment by uryelah** [comment]
Great job with all the review Nnamdi!

------
## Your project is approved! 🎊 🥅 💛 
### 
**You may close this Pull Request and merge the changes**

----

**Keep being an awesome dev and good luck with your next project!**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Pull request merged**
